name: Verify and Install IPs

on:
  push:
  workflow_dispatch:

jobs:
  verify_install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        pip install ipmgr

    - name: Read and process JSON
      id: process_json
      run: |
        # Extract IP names and their latest version
        jq -r 'to_entries[] | "\(.key) \(.value.release | keys_unsorted | .[0])"' verified_IPs.json > ip_versions.txt
  
    - name: Install and verify IPs
      run: |
        # Loop through each IP and version
        while read -r NAME VERSION; do
          echo "Processing $NAME with version $VERSION"
          ipm install "$NAME"
          ipm check-ip --ip-root ~/.ipm/"$NAME"/"$VERSION" --ip-name "$NAME"
        done < ip_versions.txt

      shell: bash
